[package]
name = "authz-sys"
version = "0.1.0"
authors = ["Matthieu Buffet <matthieu@buffet.re>"]
edition = "2018"
publish = false

[dependencies]
winapi = { version = "0.3.8", features = [ "winnt", "minwinbase" ] }
